//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPathTeam.BasicTypes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPathTeam.BasicTypes.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new item to a list by modifying it.
        /// </summary>
        internal static string AddListItem_Description {
            get {
                return ResourceManager.GetString("AddListItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add List Item.
        /// </summary>
        internal static string AddListItem_DisplayName {
            get {
                return ResourceManager.GetString("AddListItem_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string AddListItem_Property_InputList {
            get {
                return ResourceManager.GetString("AddListItem_Property_InputList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string AddListItem_Property_Item {
            get {
                return ResourceManager.GetString("AddListItem_Property_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts an input date with basic operations like adding a number of days.
        /// </summary>
        internal static string AdjustDateActivity_Description {
            get {
                return ResourceManager.GetString("AdjustDateActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Date.
        /// </summary>
        internal static string AdjustDateActivity_DisplayName {
            get {
                return ResourceManager.GetString("AdjustDateActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted date.
        /// </summary>
        internal static string AdjustDateActivity_Property_AdjustedDate {
            get {
                return ResourceManager.GetString("AdjustDateActivity_Property_AdjustedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust method.
        /// </summary>
        internal static string AdjustDateActivity_Property_AdjustMethod {
            get {
                return ResourceManager.GetString("AdjustDateActivity_Property_AdjustMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string AdjustDateActivity_Property_InputDate {
            get {
                return ResourceManager.GetString("AdjustDateActivity_Property_InputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string AdjustDateActivity_Property_Unit {
            get {
                return ResourceManager.GetString("AdjustDateActivity_Property_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string AdjustDateActivity_Property_Value {
            get {
                return ResourceManager.GetString("AdjustDateActivity_Property_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string ExtractText_Property_InputText {
            get {
                return ResourceManager.GetString("ExtractText_Property_InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to the left.
        /// </summary>
        internal static string ExtractText_Property_LeftText {
            get {
                return ResourceManager.GetString("ExtractText_Property_LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string ExtractText_Property_Result {
            get {
                return ResourceManager.GetString("ExtractText_Property_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to the right.
        /// </summary>
        internal static string ExtractText_Property_RightText {
            get {
                return ResourceManager.GetString("ExtractText_Property_RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regular expressions.
        /// </summary>
        internal static string ExtractText_Property_UseRegex {
            get {
                return ResourceManager.GetString("ExtractText_Property_UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts part of a text that is surrounded by some known text.
        /// </summary>
        internal static string ExtractTextActivity_Description {
            get {
                return ResourceManager.GetString("ExtractTextActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text.
        /// </summary>
        internal static string ExtractTextActivity_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom format.
        /// </summary>
        internal static string FormatDate_Property_Custom {
            get {
                return ResourceManager.GetString("FormatDate_Property_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022-03-02 16:08:01
        ///
        ///yyyy - 2022
        ///M - 3
        ///MM - 03
        ///MMM - Mar
        ///d - 2
        ///dd - 02
        ///HH - 16
        ///H - 4
        ///mm - 08
        ///m - 8
        ///ss - 01
        ///s - 1
        ///tt - PM
        ///t - P.
        /// </summary>
        internal static string FormatDate_Property_CustomTooltip {
            get {
                return ResourceManager.GetString("FormatDate_Property_CustomTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string FormatDate_Property_Date {
            get {
                return ResourceManager.GetString("FormatDate_Property_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string FormatDate_Property_Format {
            get {
                return ResourceManager.GetString("FormatDate_Property_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string FormatDate_Property_Text {
            get {
                return ResourceManager.GetString("FormatDate_Property_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats a date as a text using a certain pattern.
        /// </summary>
        internal static string FormatDateActivity_Description {
            get {
                return ResourceManager.GetString("FormatDateActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Date.
        /// </summary>
        internal static string FormatDateActivity_DisplayName {
            get {
                return ResourceManager.GetString("FormatDateActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats a number as a text displaying a certain number of digits and custom decimals and thousands separators.
        /// </summary>
        internal static string FormatNumber_Description {
            get {
                return ResourceManager.GetString("FormatNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Number.
        /// </summary>
        internal static string FormatNumber_DisplayName {
            get {
                return ResourceManager.GetString("FormatNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimals.
        /// </summary>
        internal static string FormatNumber_Property_Decimals {
            get {
                return ResourceManager.GetString("FormatNumber_Property_Decimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal separator.
        /// </summary>
        internal static string FormatNumber_Property_DecimalSeparator {
            get {
                return ResourceManager.GetString("FormatNumber_Property_DecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string FormatNumber_Property_Number {
            get {
                return ResourceManager.GetString("FormatNumber_Property_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string FormatNumber_Property_Text {
            get {
                return ResourceManager.GetString("FormatNumber_Property_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousands separator.
        /// </summary>
        internal static string FormatNumber_Property_ThousandSeparator {
            get {
                return ResourceManager.GetString("FormatNumber_Property_ThousandSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a random number between From and To.
        /// </summary>
        internal static string GenerateRandomNumber_Description {
            get {
                return ResourceManager.GetString("GenerateRandomNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Random Number.
        /// </summary>
        internal static string GenerateRandomNumber_DisplayName {
            get {
                return ResourceManager.GetString("GenerateRandomNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string GenerateRandomNumber_Property_From {
            get {
                return ResourceManager.GetString("GenerateRandomNumber_Property_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Number.
        /// </summary>
        internal static string GenerateRandomNumber_Property_RandomNumber {
            get {
                return ResourceManager.GetString("GenerateRandomNumber_Property_RandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string GenerateRandomNumber_Property_To {
            get {
                return ResourceManager.GetString("GenerateRandomNumber_Property_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string GetDateFromText_Property_Culture {
            get {
                return ResourceManager.GetString("GetDateFromText_Property_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (Text).
        /// </summary>
        internal static string GetDateFromText_Property_InputText {
            get {
                return ResourceManager.GetString("GetDateFromText_Property_InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string GetDateFromText_Property_OutDate {
            get {
                return ResourceManager.GetString("GetDateFromText_Property_OutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforms a given text to a date type.
        /// </summary>
        internal static string GetDateFromTextActivity_Description {
            get {
                return ResourceManager.GetString("GetDateFromTextActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Date From Text.
        /// </summary>
        internal static string GetDateFromTextActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetDateFromTextActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string GetNumberFromText_Property_InputText {
            get {
                return ResourceManager.GetString("GetNumberFromText_Property_InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string GetNumberFromText_Property_Number {
            get {
                return ResourceManager.GetString("GetNumberFromText_Property_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal separator.
        /// </summary>
        internal static string GetNumberFromText_Property_Separator {
            get {
                return ResourceManager.GetString("GetNumberFromText_Property_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforms a text into a number.
        /// </summary>
        internal static string GetNumberFromTextActivity_Description {
            get {
                return ResourceManager.GetString("GetNumberFromTextActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Number From Text.
        /// </summary>
        internal static string GetNumberFromTextActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetNumberFromTextActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the time between two dates in seconds/minutes/etc.
        /// </summary>
        internal static string GetTimeBetweenDatesActivity_Description {
            get {
                return ResourceManager.GetString("GetTimeBetweenDatesActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Time Between Dates.
        /// </summary>
        internal static string GetTimeBetweenDatesActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetTimeBetweenDatesActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string GetTimeBetweenDatesActivity_Property_EndDate {
            get {
                return ResourceManager.GetString("GetTimeBetweenDatesActivity_Property_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string GetTimeBetweenDatesActivity_Property_Interval {
            get {
                return ResourceManager.GetString("GetTimeBetweenDatesActivity_Property_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string GetTimeBetweenDatesActivity_Property_StartDate {
            get {
                return ResourceManager.GetString("GetTimeBetweenDatesActivity_Property_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string GetTimeBetweenDatesActivity_Property_Time {
            get {
                return ResourceManager.GetString("GetTimeBetweenDatesActivity_Property_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string GetTimeBetweenDatesActivity_Property_Unit {
            get {
                return ResourceManager.GetString("GetTimeBetweenDatesActivity_Property_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimals.
        /// </summary>
        internal static string RoundNumber_Property_Decimals {
            get {
                return ResourceManager.GetString("RoundNumber_Property_Decimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string RoundNumber_Property_InputNumber {
            get {
                return ResourceManager.GetString("RoundNumber_Property_InputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string RoundNumber_Property_Result {
            get {
                return ResourceManager.GetString("RoundNumber_Property_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds an input number to a specific number of digits.
        /// </summary>
        internal static string RoundNumberActivity_Description {
            get {
                return ResourceManager.GetString("RoundNumberActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Number.
        /// </summary>
        internal static string RoundNumberActivity_DisplayName {
            get {
                return ResourceManager.GetString("RoundNumberActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string SearchAndReplaceInText_Property_InputText {
            get {
                return ResourceManager.GetString("SearchAndReplaceInText_Property_InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with.
        /// </summary>
        internal static string SearchAndReplaceInText_Property_Replace {
            get {
                return ResourceManager.GetString("SearchAndReplaceInText_Property_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resulted text.
        /// </summary>
        internal static string SearchAndReplaceInText_Property_Result {
            get {
                return ResourceManager.GetString("SearchAndReplaceInText_Property_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        internal static string SearchAndReplaceInText_Property_Search {
            get {
                return ResourceManager.GetString("SearchAndReplaceInText_Property_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regular expressions.
        /// </summary>
        internal static string SearchAndReplaceInText_Property_UseRegex {
            get {
                return ResourceManager.GetString("SearchAndReplaceInText_Property_UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces a given search text with another text in the input text. The activity can also be used with regular expressions (regex).
        /// </summary>
        internal static string SearchAndReplaceInTextActivity_Description {
            get {
                return ResourceManager.GetString("SearchAndReplaceInTextActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search And Replace In Text.
        /// </summary>
        internal static string SearchAndReplaceInTextActivity_DisplayName {
            get {
                return ResourceManager.GetString("SearchAndReplaceInTextActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextLength_Property_InputText {
            get {
                return ResourceManager.GetString("TextLength_Property_InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string TextLength_Property_Length {
            get {
                return ResourceManager.GetString("TextLength_Property_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the length, in characters, of the input text.
        /// </summary>
        internal static string TextLengthActivity_Description {
            get {
                return ResourceManager.GetString("TextLengthActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Length.
        /// </summary>
        internal static string TextLengthActivity_DisplayName {
            get {
                return ResourceManager.GetString("TextLengthActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextToLowercase_Property_InputText {
            get {
                return ResourceManager.GetString("TextToLowercase_Property_InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase text.
        /// </summary>
        internal static string TextToLowercase_Property_LowercaseText {
            get {
                return ResourceManager.GetString("TextToLowercase_Property_LowercaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts the input text to lowercase.
        /// </summary>
        internal static string TextToLowercaseActivity_Description {
            get {
                return ResourceManager.GetString("TextToLowercaseActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text To lowercase.
        /// </summary>
        internal static string TextToLowercaseActivity_DisplayName {
            get {
                return ResourceManager.GetString("TextToLowercaseActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextToUppercase_Property_InputText {
            get {
                return ResourceManager.GetString("TextToUppercase_Property_InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPERCASE text.
        /// </summary>
        internal static string TextToUppercase_Property_UppercaseText {
            get {
                return ResourceManager.GetString("TextToUppercase_Property_UppercaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts the input text to UPPERCASE.
        /// </summary>
        internal static string TextToUppercaseActivity_Description {
            get {
                return ResourceManager.GetString("TextToUppercaseActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text To UPPERCASE.
        /// </summary>
        internal static string TextToUppercaseActivity_DisplayName {
            get {
                return ResourceManager.GetString("TextToUppercaseActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string TrimText_Property_Direction {
            get {
                return ResourceManager.GetString("TrimText_Property_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TrimText_Property_InputText {
            get {
                return ResourceManager.GetString("TrimText_Property_InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimmed text.
        /// </summary>
        internal static string TrimText_Property_TrimmedText {
            get {
                return ResourceManager.GetString("TrimText_Property_TrimmedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes leading and trailing white-space characters from the input text.
        /// </summary>
        internal static string TrimTextActivity_Description {
            get {
                return ResourceManager.GetString("TrimTextActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Text.
        /// </summary>
        internal static string TrimTextActivity_DisplayName {
            get {
                return ResourceManager.GetString("TrimTextActivity_DisplayName", resourceCulture);
            }
        }
    }
}
